Implement --target-attribute-path
tweag/nixtract pull request #10
Opened 2023-12-08 13:26 UTC by ErinvanderVeen

This PR adds the `--target-attribute-path` to the cli, allowing the extraction of a predetermined attribute path.

2023-12-12 11:23 UTC, GuillaumeDesforges requested changes
Looks good! Just some nitpicking on naming.

2023-12-12 11:23 UTC, GuillaumeDesforges commented on nixtract/cli.py
> +    help="The the attribute path of the provided attribute set to evaluate",
```suggestion
    help="The attribute path of the provided attribute set to evaluate",
```

2023-12-12 11:23 UTC, GuillaumeDesforges commented on README.md
> +  --target-attribute-path TEXT  The the attribute path of the provided
```suggestion
  --target-attribute-path TEXT  The attribute path of the provided
```

2023-12-12 11:23 UTC, GuillaumeDesforges commented on nixtract/find-attribute-paths.nix
> +  targetAttribute = builtins.getEnv "TARGET_ATTRIBUTE_PATH";
_beware my nitpicking_ :smile: 

```suggestion
  targetAttributePath = builtins.getEnv "TARGET_ATTRIBUTE_PATH";
```

2023-12-12 11:23 UTC, GuillaumeDesforges commented on nixtract/find-attribute-paths.nix
> +  targetPackage =
I'm not convinced we could call it a "package".
I would rather see it as the "root" value from which we recurse.

```suggestion
  targetRootValue =
```

2023-12-13 10:39 UTC, ErinvanderVeen commented
Nitpicking is good!

2023-12-13 18:42 UTC, GuillaumeDesforges approved these changes

2023-12-13 19:52 UTC, merged